# Generated by Django 5.0.2 on 2024-02-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_genre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_link',
            field=models.URLField(default='https://open.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP'),
            preserve_default=False,
        ),
    ]
