# Generated by Django 5.0.2 on 2024-02-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_spotify_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='name',
        ),
    ]
