# Generated by Django 5.0.2 on 2024-02-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_rename_artist_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='average_rating',
            field=models.FloatField(default=4.5),
            preserve_default=False,
        ),
    ]
