# Generated by Django 5.0.2 on 2024-02-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_writer', models.CharField(max_length=100)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('news_detail', models.TextField()),
                ('news_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
