# Generated by Django 5.0.2 on 2024-02-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_user_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_messages',
            old_name='emain',
            new_name='email',
        ),
    ]
