# Generated by Django 5.0.2 on 2024-02-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_album_artist_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='album_artist',
        ),
    ]
