# Generated by Django 5.0.2 on 2024-02-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_rename_user_messages_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
