# Generated by Django 5.0.2 on 2024-02-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_album_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='review',
        ),
    ]
